info:
  contact: {}
paths:
  /user:
    get:
      consumes:
      - application/json
      description: Create A user
      produces:
      - application/json
      responses: {}
      summary: Create User
      tags:
      - Create User
swagger: "2.0"
